Added note that an Azure DevOps data connector supports only data fro…
MicrosoftDocs/azure-devops-docs pull request #10614
Opened 2021-04-28 14:17 UTC by dronkoff

Added note that an Azure DevOps data connector supports only data from Boards. 
See Bug #1812449 for details.

2021-04-28 14:17 UTC, PRMerger12 commented
@dronkoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-04-29 22:43 UTC, KathrynEE requested changes
@dronkoff - Thank you for this contribution. I can't approve it, however, as it contains a stacked Note, which is against our content guidance.  You can choose to close this and I can update the topic from our private repo, azure-devops-docs-pr, or you can fix it by combining the two important notes into one. By the way, we ask Microsoft personnel to make updates to content to our private repo. You can learn how by reviewing [Contributors guide, Setup a GitHub account](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master).

2021-05-26 00:45 UTC, KathrynEE approved these changes

2021-05-26 15:21 UTC, PRMerger19 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-05-26 15:23 UTC, ktoliver commented
We made the requested changes and will merge with the indicated approval. Thanks.

2021-05-26 15:23 UTC, merged