Update ci-triggers5.md
MicrosoftDocs/azure-devops-docs pull request #11364
Opened 2021-09-17 11:48 UTC by PavloAndriiesh

Update tips about wildcard use cases according to latest release notes regarding wildcards in trigger paths: https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#support-for-wild-cards-in-path-filters

2021-09-17 11:48 UTC, PRMerger7 commented
@PavloAndriiesh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-17 13:03 UTC, vijayma requested changes

2021-09-17 13:03 UTC, vijayma commented on docs/pipelines/repos/includes/ci-triggers5.md
> +* For branches, tags and wildcards a wildcard may appear anywhere in the pattern.
For branches and tags, a wildcard may appear anywhere in the pattern.

2021-09-17 13:08 UTC, PRMerger19 commented
@PavloAndriiesh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-17 15:46 UTC, ktoliver commented
#label:"aq-pr-triaged"

2021-09-20 11:35 UTC, vijayma approved these changes

2021-09-20 16:47 UTC, PRMerger4 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-20 16:47 UTC, merged