Update variables.md to elaborate on variable syntax usage.
MicrosoftDocs/azure-devops-docs pull request #14137
Opened 2024-09-05 20:24 UTC by JFolberth

This pull request includes updates to the documentation in `docs/pipelines/process/variables.md` to improve clarity on variable usage in Azure DevOps pipelines. The most important changes focus on refining the guidance for using macro and template syntax.

Documentation updates:

* Clarified that macro syntax should be used for providing secure strings or predefined variable inputs for a task.
* Expanded the explanation on template variables, emphasizing their use for fully injecting variable values at pipeline compilation and noting that template syntax should not be used for sensitive values.

2024-09-05 20:41 UTC, Court72 commented
@juliakm

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-09-30 14:18 UTC, JFolberth commented
@juliakm Are you able to review?

2024-09-30 17:42 UTC, juliakm requested changes
Thanks for your contribution! Can you make a couple of small changes?

2024-09-30 17:42 UTC, juliakm commented on docs/pipelines/process/variables.md
> +Use macro syntax if you're providing a secure string or a [predefined variable](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) input for a task.
```suggestion
Use macro syntax if you're providing a secure string or a [predefined variable](/azure/devops/pipelines/build/variables) input for a task. 
```

2024-10-14 17:54 UTC, JFolberth commented
@juliakm Updates were made as requested.

2024-11-06 19:58 UTC, juliakm approved these changes
Thanks for the updates!

2024-11-06 19:58 UTC, juliakm commented
#sign-off

2024-11-06 21:33 UTC, merged